# Project information
site_name: "John's Cheatsheets"
site_description: 'A collection of cheatsheets and code snippets.'
site_author: 'S. John Cruchon-Dupeyrat'
site_url: 'http://john-cd.com/cheatsheets/'

# Repository
repo_name: 'john-cd/cheatsheets'
repo_url: 'https://github.com/john-cd/cheatsheets'
edit_uri: edit/master/docs_src/

# Copyright
copyright: 'Copyright &copy; 2017-2021 S. John Cruchon-Dupeyrat'

# Documentation sources and theme
docs_dir: 'docs_src'
site_dir: 'docs'

theme:
  name: material  
  palette:
    primary: deep orange
    accent: orange
  font:
    text: Roboto
    code: Roboto Mono  
  features:
    - navigation.tabs
    - header.autohide

# Options
extra:
  social:
    - icon: fontawesome/brands/github
      link: 'https://github.com/john-cd'
    - icon: fontawesome/brands/twitter
      link: 'https://twitter.com/sjncd'
    - icon: fontawesome/brands/linkedin
      link: 'https://www.linkedin.com/in/scdupeyrat/'
#  disqus: 'your-shortname'

# Google Analytics
google_analytics:
  - 'UA-92780605-1'
  - 'auto'

# Extensions
markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true