# Project information
site_name: "John's Cheatsheets"
site_description: 'A collection of cheatsheets and code snippets.'
site_author: 'S. John Cruchon-Dupeyrat'
site_url: 'http://john-cd.com/cheatsheets/'

# Repository
repo_name: 'john-cd/cheatsheets'
repo_url: 'https://github.com/john-cd/cheatsheets'
edit_uri: edit/master/docs_src/

# Copyright
copyright: 'Copyright &copy; 2017-2020 S. John Cruchon-Dupeyrat'

# Documentation sources and theme
docs_dir: 'docs_src'
site_dir: 'docs'

theme:
#  name: readthedocs
 name: material  
 palette:
   primary: 'deep orange'
   accent: 'orange'
 font:
   text: 'Roboto'
   code: 'Roboto Mono'
#  feature:
#    tabs: true
# logo: 'images/logo.svg'
# favicon: 'assets/images/favicon.ico   

# Options
extra:
  social:
    - type: 'github'
      link: 'https://github.com/john-cd'
    - type: 'twitter'
      link: 'https://twitter.com/sjncd'
    - type: 'linkedin'
      link: 'https://www.linkedin.com/in/scdupeyrat/'
#  disqus: 'your-shortname'
      
      
# Google Analytics
google_analytics:
  - 'UA-92780605-1'
  - 'auto'

# Extensions
markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true
